name: Build Jailed Tweak

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Projeyi Kopyala (Checkout)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Theos Ortamını Kur
        uses: beerpiss/theos-action@v1

      - name: theos-jailed Modülünü Yükle
        run: |
          git clone https://github.com/kabiroberai/theos-jailed.git $THEOS/mod/jailed
          cd $THEOS/mod/jailed && ./install

      - name: Projeyi Derle (Make)
        run: |
          make package
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Çıktı Dosyasını (Artifact) Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: Jailed-Tweak-Package
          path: packages/*.deb
